# Generated by Django 2.2.5 on 2019-10-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickmed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospital_phone',
        ),
    ]
