# Generated by Django 2.2.5 on 2019-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmed', '0003_auto_20191004_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=300)),
            ],
        ),
    ]
