# Generated by Django 2.2.5 on 2019-10-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickmed', '0004_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
