# Generated by Django 2.2.5 on 2019-10-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmed', '0006_auto_20191005_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.CharField(max_length=300),
        ),
    ]
