# Generated by Django 2.2.5 on 2019-10-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickmed', '0008_auto_20191005_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
